package dz.minagri.stat.production.enumeration;

public enum TypeEspeceCereal {
    BLEDURE, BLETENDRE, ORGE, AVOINE, TRITICALE, MAIS, SORGHO, FEVESFEVEROLLE, POIS, LENTILLE, POISCHICHE, HARICOT, GESSESGUERFALLA, TREFLE, PDT_MULTIPLICATION, VESCE, LUSERNE, TOMATES_INDUSTR, TABAC, ARACHIDE, MENTHE, PDT_CONSOMMATION, CARROTE, TOMATE_PLCHAMP, TOMATE_SERRES, OIGNON, MELON, PASTEQUE, ARTICHAUT, PIMENT, POIVRON, CONCOMBRE, COURGETTE, AUBERGINE, CHOUXVERT, CHOUXFLEUR, NAVET, AIL, PETITSPOIS,
    FENOUIL, SALAD, BETRAVE, FRAISE;
}
