package dz.minagri.stat.customer.enumeration;

public enum RoleType {
    AUTRES, FELLAH_EXPLOITANT, USEROLE_TYPE, CREATOR, EDITOR,
    INTERNE, AGENT_CV, AGENT_SUBDEV, AGENT_DSA, ADMIN, SUPERVISEUR,
    AGENT_MINIST, EXTERNE;

}